config/routes.rb
Rails.application.routes.draw do
  #get 'password_resets/new'
  #get 'password_resets/edit'
  #get 'sessions/new'
  root 'static_pages#home'
  #get  'static_pages/home'
  

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/signin',   to: 'sessions#new'
  post   '/signin',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :posts , only: [:new, :create, :index]

  #resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to  :user

    validates :title,  presence: true, length: { minimum: 5 }
    validates :message, presence: true, length: { maximum: 255 }

end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts

    attr_accessor :remember_token    
    before_create :create_remember_digest
    validates :name, presence: true, length: {maximum:50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255}, format:{ with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}
    has_secure_password

    # Returns the hash digest of the given string.
    def User.digest(token)
        Digest::SHA1.hexdigest(token.to_s)
    end

    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end


    def forget
        update_attribute(:remember_digest, nil)
    end   
    
     # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        digest == Digest::SHA1.hexdigest(token)
    end


    #------------- private ------------------------

    private

    # Converts email to all lower-case.
    #def downcase_email
    #      self.email = email.downcase
    #end

    
    def create_remember_digest
          self.remember_token   = User.new_token
          self.remember_digest = User.digest(remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in_user
    
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def log_in(user)
        session[:user_id] = user.id
    end


    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def current_user?(user)
        user == current_user()
    end

    def logged_in?
      not current_user.nil?
    end

    def current_user
        if (user_id = session[:user_id]) #its really an equal sign
          @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
          #raise       # The tests still pass, so this branch is currently untested.
          user = User.find_by(id: user_id)
          if user && user.authenticated?(:remember, cookies[:remember_token])
            log_in(user)
            @current_user = user
          end
        end
    end
    
    def current_user=(user)
        @current_user = user
    end

    def signout
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def logged_in_user
        unless logged_in?
          flash[:danger] = "Please log in."
          redirect_to signin_url
        end
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :logged_in_user, only: [:new, :create]

    def index
      @posts = Post.all.paginate(page: params[:page])
    end

    def new 
        @post = Post.new
    end

    def create
        @post = current_user.posts.build(post_params) 
        if @post.save
          flash[:info] = "Post succesfully created"
          redirect_to posts_path
        else
          render 'new'
        end
    end


    private

    def post_params
      params.require(:post).permit(:title, :message)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    
  
    def create   
      @user = User.find_by(email: params[:session][:email].downcase)
      if @user && @user.authenticate(params[:session][:password])
          log_in(@user)
          current_user()
          params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
          redirect_to root_url
      else
        # Create an error message.
        flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
        render 'new'
      end
    end


    def destroy
        signout() if current_user() != nil
        redirect_to root_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          flash[:info] = "Account succesfully created"
          redirect_to root_url
        else
          render 'new'
        end
    end


    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "All Posts", "/posts/" %></li>        
         <% if current_user() != nil %>
            <li>
              <%= link_to "Create Post", "/posts/new" %>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>         
        <% else %>
          <li><%= link_to "New User", "/users/new" %></li>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
        
      </ul>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <%= render 'layouts/header' %>
    </header>

    <div class="container container2">
    <br/> <br/><br/><br/><br/>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<% provide(:title, 'All Posts') %>
<h1>All Posts</h1>

<%= will_paginate %>

<ul class="users">
  <% @posts.each do |post| %>
    <li>
        <b> <%= post.title %> </b>
        <%  if !current_user.nil? %>
              ( by <u><%= post.user.name %></u>)
        <% end %>
        <p> <%= post.message %> </p>
        
    </li>
  <% end %>
</ul> 

app/views/posts/new.html.erb
<% provide(:title, "Create new Post") %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <h1>Create Post</h1>
    <%= form_for(:post, url: posts_path) do |f| %>
      <%= render 'shared/post_error_messages', object: @post %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :message %>
      <%= f.text_area :message, class: 'form-control' %>

      <%= f.submit "Create new Post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@post.errors.count, "error") %>.
    </div>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h1>Welcome to Members Only</h1>
  
    <% user = current_user()  %>
    <% if user != nil %>           
        Logged in as <b><%= user.name  %></b>
    <% end %>
  
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>